version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Starting install phase..."
      - echo "Installing dependencies..."
      - npm install --silent --no-progress -g serverless
  build:
    commands:
      - set -e
      - echo "Starting build phase..."
      - echo "ENVIRONMENT: ${ENVIRONMENT:-dev}"
      - echo "REGION: ${REGION:-us-east-1}"
      - serverless deploy --stage ${ENVIRONMENT:-dev} --region ${REGION:-us-east-1} --verbose
      - echo "Build phase completed successfully."
  post_build:
    commands:
      - echo "Post build phase completed."
